<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site avec bouton</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f0f0f0;
        }
        .container {
            text-align: center;
        }
        .btn {
            padding: 15px 30px;
            font-size: 18px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        .btn:hover {
            background-color: #45a049;
        }
        .message {
            margin-top: 20px;
            font-size: 20px;
            font-weight: bold;
            display: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <button id="moneyButton" class="btn">Cliquez pour me faire gagner de l'argent</button>
        <div id="message" class="message">Bravo tu as financé Tel Aviv, bravo Rimsha</div>
    </div>

    <script>
        document.getElementById('moneyButton').addEventListener('click', function() {
            document.getElementById('message').style.display = 'block';
        });
    </script>
</body>
</html>
